import type { Product, Order, Payment } from "./types";

const agaroGlucose1 = "/agaro-glucose-monitoring.jpg";
const careTouchGlucose1 = "/caretouch-glucose-monitoring.jpeg";
const careTouchGlucose2 = "/caretouch-glucose-monitoring-2.jpg";
const easyHomeGlucose = "/easy-home-glucose-monitoring.webp";
const omronBloodPressure = "/omron-blood-pressure-monitor.jpg";
const omronBloodPressure2 = "/omron-blood-pressure-monitor-2.jpg";
const omronBloodPressure3 = "/omron-blood-pressure-monitor-3.webp";
const omronBloodPressure4 = "/omron-blood-pressure-monitor-4.jpg";
const pangaBloodPressure = "/panga-blood-pressure-monitor.webp";
const pangaBloodPressure2 = "/panga-blood-pressure-monitor-2.webp";
const pangaBloodPressure3 = "/panga-blood-pressure-monitor-3.webp";

const vagKit = "/VagKit.png";
const hivKit = "/hiv.png";
const hepBKit = "/HepB.png";
const gonnorheaKit = "/Gonnorhea.png";
const malariaKit = "/Malaria2.png";
const typhoidKit = "/Typhoid.png";
const drugAbuseKit = "/DrugAbuse.png";
const pregnacy = "/Pregenacy.png";
const ovulationKit = "/Ovulation.png";
const hivTest = "/hiv.png";
const syphilisTest = "/syphilis.png";

const firstAid1 = "/firstAid.avif";
const firstAid2 = "/firstAid2.png";
const firstAid3 = "/firstAid3.png";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Malaria Test Kit",
    description:
      "Rapid diagnostic test for malaria detection. Results in 15-20 minutes.",
    brand: "OraSure Technologies",
    category: "Rapid Test Kits",
    price: 157.0,
    images: [malariaKit],
    inStock: true,
    normalRange: "Negative",
    unit: "Box",
    stockQuantity: 15,
    imageUrl: malariaKit,
  },
  {
    id: "2",
    name: "Digital Blood Pressure Monitor",
    description:
      "Automatic upper arm blood pressure monitor with digital display and memory function.",
    brand: "Omron",
    category: "Medical Devices",
    price: 450.0,
    images: [
      omronBloodPressure,
      omronBloodPressure2,
      omronBloodPressure3,
      omronBloodPressure4,
    ],
    inStock: true,
    normalRange: "120/80 mmHg",
    unit: "Device",
    stockQuantity: 8,
    imageUrl: omronBloodPressure,
  },
  {
    id: "3",
    name: "Glucose Test Strips",
    description:
      "Compatible test strips for glucose monitoring devices. Pack of 50.",
    brand: "AccuChek",
    category: "Diabetic Supplies",
    price: 320.0,
    images: [
      careTouchGlucose1,
      careTouchGlucose2,
      easyHomeGlucose,
      agaroGlucose1,
    ],
    inStock: true,
    normalRange: "70-140 mg/dL",
    unit: "Pack",
    stockQuantity: 23,
    imageUrl: careTouchGlucose1,
  },
  {
    id: "5",
    name: "Digital Thermometer",
    description:
      "Fast-reading digital thermometer with fever alarm and memory function.",
    brand: "Braun",
    category: "Medical Devices",
    price: 120.0,
    images: [pangaBloodPressure, pangaBloodPressure2, pangaBloodPressure3],
    inStock: true,
    normalRange: "36.5-37.5°C",
    unit: "Device",
    stockQuantity: 12,
    imageUrl: pangaBloodPressure,
  },
  {
    id: "6",
    name: "Pregnancy Test Kit",
    description:
      "Early detection pregnancy test with over 99% accuracy. Results in 3 minutes.",
    brand: "ClearBlue",
    category: "Rapid Test Kits",
    price: 150.0,
    images: [pregnacy],
    inStock: false,
    normalRange: "N/A",
    unit: "Pack of 2",
    stockQuantity: 0,
    imageUrl: pregnacy,
  },
  {
    id: "7",
    name: "HIV Self-Test Kit",
    description:
      "Rapid HIV antibody test for home use. Results in 15-20 minutes with 99.9% accuracy.",
    brand: "OraSure Technologies",
    category: "Rapid Test Kits",
    price: 580.0,
    images: [hivKit, hivTest],
    inStock: true,
    normalRange: "Non-reactive",
    unit: "Single Test",
    stockQuantity: 25,
    imageUrl: hivKit,
  },
  {
    id: "8",
    name: "Hepatitis B Test Kit",
    description:
      "Rapid diagnostic test for Hepatitis B surface antigen detection. Results in 15 minutes.",
    brand: "Standard Diagnostics",
    category: "Rapid Test Kits",
    price: 210.0,
    images: [hepBKit],
    inStock: true,
    normalRange: "Non-reactive",
    unit: "Single Test",
    stockQuantity: 18,
    imageUrl: hepBKit,
  },
  {
    id: "9",
    name: "Typhoid Test Kit",
    description:
      "Rapid test for typhoid fever detection. Detects Salmonella typhi antibodies in 10-15 minutes.",
    brand: "CTK Biotech",
    category: "Rapid Test Kits",
    price: 184.0,
    images: [typhoidKit],
    inStock: true,
    normalRange: "Negative",
    unit: "Single Test",
    stockQuantity: 32,
    imageUrl: typhoidKit,
  },
  {
    id: "10",
    name: "Gonorrhea Test Kit",
    description:
      "Home test kit for gonorrhea detection. Easy to use with results in 20 minutes.",
    brand: "LetsGetChecked",
    category: "Rapid Test Kits",
    price: 420.0,
    images: [gonnorheaKit],
    inStock: true,
    normalRange: "Negative",
    unit: "Single Test",
    stockQuantity: 14,
    imageUrl: gonnorheaKit,
  },
  {
    id: "11",
    name: "Syphilis Test Kit",
    description:
      "Rapid syphilis test for early detection. Detects Treponema pallidum antibodies in 15 minutes.",
    brand: "Bioline",
    category: "Rapid Test Kits",
    price: 360.0,
    images: [syphilisTest],
    inStock: true,
    normalRange: "Non-reactive",
    unit: "Single Test",
    stockQuantity: 20,
    imageUrl: syphilisTest,
  },
  {
    id: "12",
    name: "Drug Abuse Test Kit",
    description:
      "Multi-panel drug screening test for cocaine, marijuana, amphetamines, and opiates. Results in 5 minutes.",
    brand: "DrugConfirm",
    category: "Rapid Test Kits",
    price: 320.0,
    images: [drugAbuseKit],
    inStock: true,
    normalRange: "Negative",
    unit: "Single Test",
    stockQuantity: 28,
    imageUrl: drugAbuseKit,
  },
  {
    id: "13",
    name: "Ovulation Test Kit",
    description:
      "Fertility test kit to predict ovulation. Detects LH surge with over 99% accuracy.",
    brand: "First Response",
    category: "Rapid Test Kits",
    price: 8.0,
    images: [ovulationKit],
    inStock: true,
    normalRange: "Variable",
    unit: "Pack of 7",
    stockQuantity: 35,
    imageUrl: ovulationKit,
  },
  {
    id: "14",
    name: "Vaginal Infection Test Kit",
    description:
      "Home test for bacterial vaginosis and yeast infections. Results in 10 minutes.",
    brand: "Monistat",
    category: "Rapid Test Kits",
    price: 250.0,
    images: [vagKit],
    inStock: true,
    normalRange: "Normal pH 3.8-4.5",
    unit: "Pack of 2",
    stockQuantity: 22,
    imageUrl: vagKit,
  },
  {
    id: "15",
    name: "Basic First Aid Kit",
    description:
      "Essential first aid supplies for minor injuries. Includes bandages, antiseptic wipes, gauze pads, and medical tape.",
    brand: "Johnson & Johnson",
    category: "Medical Materials",
    price: 200.0,
    images: [firstAid1],
    inStock: true,
    normalRange: "N/A",
    unit: "Basic Kit",
    stockQuantity: 35,
    imageUrl: firstAid1,
  },
  {
    id: "16",
    name: "Premium First Aid Kit",
    description:
      "Comprehensive first aid kit with advanced supplies including instant cold packs, burn gel, thermometer, scissors, and emergency blanket.",
    brand: "Red Cross",
    category: "Medical Materials",
    price: 200.0,
    images: [firstAid2],
    inStock: true,
    normalRange: "N/A",
    unit: "Premium Kit",
    stockQuantity: 20,
    imageUrl: firstAid2,
  },
  {
    id: "17",
    name: "Travel First Aid Kit",
    description:
      "Compact portable first aid kit perfect for travel, outdoor activities, and small spaces. Contains essential supplies in a waterproof case.",
    brand: "Adventure Medical Kits",
    category: "Medical Materials",
    price: 200.0,
    images: [firstAid3],
    inStock: true,
    normalRange: "N/A",
    unit: "Travel Kit",
    stockQuantity: 45,
    imageUrl: firstAid3,
  },
];

export const mockOrders: Order[] = [
  {
    id: "1",
    items: [
      { productId: "1", quantity: 2, price: 200.0 },
      { productId: "2", quantity: 1, price: 450.0 },
    ],
    status: "processing",
    total: 850.0,
    createdAt: new Date("2025-05-16T10:00:00Z").toISOString(),
    paymentMethod: "mobile-money",
    paymentType: "full",
    paymentDetails: {
      network: "MTN",
      accountNumber: "1234567890",
      accountName: "John Doe",
    },
    shippingAddress: {
      pharmacyName: "Health Pharmacy",
      phone: "+233123456789",
      email: "healthpharmacy@example.com",
      location: "Accra",
      streetAddress: "123 Main St",
      gpsAddress: "GA-123-4567",
    },
    tracking: [
      {
        status: "Order placed",
        date: new Date("2025-05-16T10:00:00Z").toISOString(),
      },
      {
        status: "Pending Confirmation",
        date: new Date("2025-05-16T10:05:00Z").toISOString(),
      },
    ],
  },
  {
    id: "2",
    items: [
      { productId: "3", quantity: 3, price: 320.0 },
      { productId: "5", quantity: 1, price: 120.0 },
    ],
    status: "shipped",
    total: 1080.0,
    createdAt: new Date("2025-05-15T14:30:00Z").toISOString(),
    paymentMethod: "card",
    paymentType: "full",
    paymentDetails: {
      cardLast4: "4242",
    },
    shippingAddress: {
      pharmacyName: "Care Plus Pharmacy",
      phone: "+233234567890",
      email: "care.plus@example.com",
      location: "Kumasi",
      streetAddress: "45 Hospital Road",
      gpsAddress: "AK-789-0123",
    },
    tracking: [
      {
        status: "Order placed",
        date: new Date("2025-05-15T14:30:00Z").toISOString(),
      },
      {
        status: "Confirmed",
        date: new Date("2025-05-15T14:35:00Z").toISOString(),
      },
      {
        status: "Shipped",
        date: new Date("2025-05-15T16:00:00Z").toISOString(),
      },
    ],
  },
  {
    id: "3",
    items: [{ productId: "4", quantity: 1, price: 580.0 }],
    status: "delivered",
    total: 580.0,
    createdAt: new Date("2025-05-14T09:15:00Z").toISOString(),
    deliveredAt: new Date("2025-05-14T14:30:00Z").toISOString(),
    paymentMethod: "mobile-money",
    paymentType: "half",
    paymentDetails: {
      network: "Vodafone",
      accountNumber: "0987654321",
      accountName: "Jane Smith",
    },
    shippingAddress: {
      pharmacyName: "MediLife Pharmacy",
      phone: "+233345678901",
      email: "medilife@example.com",
      location: "Tema",
      streetAddress: "15 Industrial Ave",
      gpsAddress: "GT-456-7890",
    },
    tracking: [
      {
        status: "Order placed",
        date: new Date("2025-05-14T09:15:00Z").toISOString(),
      },
      {
        status: "Confirmed",
        date: new Date("2025-05-14T09:20:00Z").toISOString(),
      },
      {
        status: "Shipped",
        date: new Date("2025-05-14T11:00:00Z").toISOString(),
      },
      {
        status: "Out for delivery",
        date: new Date("2025-05-14T13:45:00Z").toISOString(),
      },
      {
        status: "Delivered",
        date: new Date("2025-05-14T14:30:00Z").toISOString(),
      },
    ],
  },
  {
    id: "4",
    items: [{ productId: "6", quantity: 2, price: 150.0 }],
    status: "cancelled",
    total: 300.0,
    createdAt: new Date("2025-05-13T16:45:00Z").toISOString(),
    paymentMethod: "card",
    paymentType: "full",
    paymentDetails: {
      cardLast4: "1234",
    },
    shippingAddress: {
      pharmacyName: "Wellness Pharmacy",
      phone: "+233456789012",
      email: "wellness@example.com",
      location: "Cape Coast",
      streetAddress: "78 Beach Road",
      gpsAddress: "CC-234-5678",
    },
    tracking: [
      {
        status: "Order placed",
        date: new Date("2025-05-13T16:45:00Z").toISOString(),
      },
      {
        status: "Cancelled",
        date: new Date("2025-05-13T17:00:00Z").toISOString(),
      },
    ],
  },
];

export const mockPayments: Payment[] = [
  {
    id: "1",
    orderNo: "#7578558686",
    productName: "Malaria Test Kit",
    paymentType: "Full Payment",
    amount: 157.0,
    lastPaymentDate: "11th April, 2025",
    amountPaid: 157.0,
    amountRemaining: 0.0,
    status: "delivered",
    date: "20th Mar, 2025",
  },
  {
    id: "2",
    orderNo: "#7578558687",
    productName: "Digital Blood Pressure Monitor",
    paymentType: "Partial",
    amount: 450.0,
    lastPaymentDate: "10th April, 2025",
    amountPaid: 300.0,
    amountRemaining: 150.0,
    status: "shipped",
    date: "19th Mar, 2025",
  },
  {
    id: "3",
    orderNo: "#7578558688",
    productName: "Glucose Test Strips",
    paymentType: "Credit",
    amount: 320.0,
    lastPaymentDate: "15th April, 2025",
    amountPaid: 100.0,
    amountRemaining: 220.0,
    status: "processing",
    date: "18th Mar, 2025",
  },
  {
    id: "4",
    orderNo: "#7578558689",
    productName: "HIV Self-Test Kit",
    paymentType: "Full Payment",
    amount: 580.0,
    lastPaymentDate: "14th April, 2025",
    amountPaid: 580.0,
    amountRemaining: 0.0,
    status: "delivered",
    date: "17th Mar, 2025",
  },
  {
    id: "5",
    orderNo: "#7578558690",
    productName: "Digital Thermometer",
    paymentType: "Full Payment",
    amount: 120.0,
    lastPaymentDate: "13th April, 2025",
    amountPaid: 120.0,
    amountRemaining: 0.0,
    status: "delivered",
    date: "16th Mar, 2025",
  },
  {
    id: "6",
    orderNo: "#7578558691",
    productName: "Digital Blood Pressure Monitor",
    paymentType: "Credit",
    amount: 450.0,
    lastPaymentDate: "12th April, 2025",
    amountPaid: 150.0,
    amountRemaining: 300.0,
    status: "processing",
    date: "15th Mar, 2025",
  },
  {
    id: "7",
    orderNo: "#7578558692",
    productName: "Malaria Test Kit",
    paymentType: "Full Payment",
    amount: 157.0,
    lastPaymentDate: "11th April, 2025",
    amountPaid: 157.0,
    amountRemaining: 0.0,
    status: "processing",
    date: "14th Mar, 2025",
  },
  {
    id: "8",
    orderNo: "#7578558693",
    productName: "Glucose Test Strips",
    paymentType: "Partial",
    amount: 320.0,
    lastPaymentDate: "10th April, 2025",
    amountPaid: 160.0,
    amountRemaining: 160.0,
    status: "shipped",
    date: "13th Mar, 2025",
  },
  {
    id: "9",
    orderNo: "#7578558694",
    productName: "Digital Blood Pressure Monitor",
    paymentType: "Credit",
    amount: 450.0,
    lastPaymentDate: "9th April, 2025",
    amountPaid: 150.0,
    amountRemaining: 300.0,
    status: "delivered",
    date: "12th Mar, 2025",
  },
  {
    id: "10",
    orderNo: "#7578558695",
    productName: "HIV Self-Test Kit",
    paymentType: "Full Payment",
    amount: 580.0,
    lastPaymentDate: "8th April, 2025",
    amountPaid: 580.0,
    amountRemaining: 0.0,
    status: "delivered",
    date: "11th Mar, 2025",
  },
  {
    id: "11",
    orderNo: "#7578558696",
    productName: "Hepatitis B Test Kit",
    paymentType: "Full Payment",
    amount: 210.0,
    lastPaymentDate: "16th April, 2025",
    amountPaid: 210.0,
    amountRemaining: 0.0,
    status: "delivered",
    date: "10th Mar, 2025",
  },
  {
    id: "12",
    orderNo: "#7578558697",
    productName: "Typhoid Test Kit",
    paymentType: "Partial",
    amount: 184.0,
    lastPaymentDate: "15th April, 2025",
    amountPaid: 92.0,
    amountRemaining: 92.0,
    status: "shipped",
    date: "9th Mar, 2025",
  },
  {
    id: "13",
    orderNo: "#7578558698",
    productName: "Gonorrhea Test Kit",
    paymentType: "Credit",
    amount: 420.0,
    lastPaymentDate: "14th April, 2025",
    amountPaid: 200.0,
    amountRemaining: 220.0,
    status: "processing",
    date: "8th Mar, 2025",
  },
  {
    id: "14",
    orderNo: "#7578558699",
    productName: "Syphilis Test Kit",
    paymentType: "Full Payment",
    amount: 360.0,
    lastPaymentDate: "17th April, 2025",
    amountPaid: 360.0,
    amountRemaining: 0.0,
    status: "delivered",
    date: "7th Mar, 2025",
  },
  {
    id: "15",
    orderNo: "#7578558700",
    productName: "Drug Abuse Test Kit",
    paymentType: "Full Payment",
    amount: 320.0,
    lastPaymentDate: "18th April, 2025",
    amountPaid: 320.0,
    amountRemaining: 0.0,
    status: "processing",
    date: "6th Mar, 2025",
  },
  {
    id: "16",
    orderNo: "#7578558701",
    productName: "Ovulation Test Kit",
    paymentType: "Partial",
    amount: 8.0,
    lastPaymentDate: "19th April, 2025",
    amountPaid: 4.0,
    amountRemaining: 4.0,
    status: "shipped",
    date: "5th Mar, 2025",
  },
  {
    id: "17",
    orderNo: "#7578558702",
    productName: "Vaginal Infection Test Kit",
    paymentType: "Full Payment",
    amount: 250.0,
    lastPaymentDate: "20th April, 2025",
    amountPaid: 250.0,
    amountRemaining: 0.0,
    status: "delivered",
    date: "4th Mar, 2025",
  },
  {
    id: "18",
    orderNo: "#7578558703",
    productName: "Basic First Aid Kit",
    paymentType: "Full Payment",
    amount: 150.0,
    lastPaymentDate: "21st April, 2025",
    amountPaid: 150.0,
    amountRemaining: 0.0,
    status: "delivered",
    date: "3rd Mar, 2025",
  },
  {
    id: "19",
    orderNo: "#7578558704",
    productName: "Premium First Aid Kit",
    paymentType: "Partial",
    amount: 350.0,
    lastPaymentDate: "22nd April, 2025",
    amountPaid: 200.0,
    amountRemaining: 150.0,
    status: "processing",
    date: "2nd Mar, 2025",
  },
  {
    id: "20",
    orderNo: "#7578558705",
    productName: "Travel First Aid Kit",
    paymentType: "Full Payment",
    amount: 80.0,
    lastPaymentDate: "23rd April, 2025",
    amountPaid: 80.0,
    amountRemaining: 0.0,
    status: "shipped",
    date: "1st Mar, 2025",
  },
];
