export interface Product {
  id: string
  name: string
  brand: string
  price: number
  description: string
  images: string[]
  category: string
  stockQuantity: number
  unit: string
  inStock: boolean
}

export const products: Product[] = [
  {
    id: "1",
    name: "Malaria Test Kit",
    brand: "Abbott",
    price: 50.0,
    description: "Rapid malaria diagnostic test kit for accurate detection",
    images: [
      "/product-images/Malaria2.png",
      "/product-images/med.png",
    ],
    category: "Test Kit",
    stockQuantity: 2,
    unit: "boxes",
    inStock: true,
  },
  {
    id: "2",
    name: "HIV Test Kit",
    brand: "Roche Diagnostics",
    price: 75.0,
    description: "Rapid HIV diagnostic test kit for early detection",
    images: [
      "/product-images/hiv.png",
      "/product-images/med.png",
    ],
    category: "Test Kit",
    stockQuantity: 2,
    unit: "boxes",
    inStock: true,
  },
  {
    id: "3",
    name: "Hepatitis B Test Kit",
    brand: "Moderna",
    price: 120.0,
    description: "Hepatitis B diagnostic test kit",
    images: [
      "/product-images/HepB.png",
      "/product-images/med.png",
    ],
    category: "Test Kit",
    stockQuantity: 0,
    unit: "kits",
    inStock: false,
  },
  {
    id: "4",
    name: "Omron Blood Pressure Monitor",
    brand: "Omron",
    price: 250.0,
    description: "Digital blood pressure monitoring device with advanced features",
    images: [
      "/product-images/omron-blood-pressure-monitor.jpg",
      "/product-images/omron-blood-pressure-monitor-2.jpg",
      "/product-images/omron-blood-pressure-monitor-3.webp",
      "/product-images/omron-blood-pressure-monitor-4.jpg",
    ],
    category: "Vital Monitoring Devices",
    stockQuantity: 5,
    unit: "units",
    inStock: true,
  },
  {
    id: "5",
    name: "Panga Blood Pressure Monitor",
    brand: "Panga",
    price: 180.0,
    description: "Reliable blood pressure monitoring device for home use",
    images: [
      "/product-images/panga-blood-pressure-monitor.webp",
      "/product-images/panga-blood-pressure-monitor-2.webp",
      "/product-images/panga-blood-pressure-monitor-3.webp",
    ],
    category: "Vital Monitoring Devices",
    stockQuantity: 10,
    unit: "units",
    inStock: true,
  },
  {
    id: "6",
    name: "Easy Home Glucose Monitor",
    brand: "Easy Home",
    price: 95.0,
    description: "Easy-to-use glucose monitoring system for diabetes management",
    images: [
      "/product-images/easy-home-glucose-monitoring.webp",
    ],
    category: "Vital Monitoring Devices",
    stockQuantity: 3,
    unit: "units",
    inStock: true,
  },
  {
    id: "7",
    name: "CareTouch Glucose Monitor",
    brand: "CareTouch",
    price: 85.0,
    description: "Advanced glucose monitoring system with test strips",
    images: [
      "/product-images/caretouch-glucose-monitoring.jpeg",
      "/product-images/caretouch-glucose-monitoring-2.jpg",
    ],
    category: "Vital Monitoring Devices",
    stockQuantity: 15,
    unit: "units",
    inStock: true,
  },
  {
    id: "8",
    name: "Agaro Glucose Monitor",
    brand: "Agaro",
    price: 75.0,
    description: "Compact glucose monitoring device for daily use",
    images: [
      "/product-images/agaro-glucose-monitoring.jpg",
    ],
    category: "Vital Monitoring Devices",
    stockQuantity: 8,
    unit: "units",
    inStock: true,
  },
  {
    id: "9",
    name: "Syphilis Test Kit",
    brand: "Abbott",
    price: 45.0,
    description: "Rapid syphilis diagnostic test kit",
    images: [
      "/product-images/syphilis.png",
      "/product-images/med.png",
    ],
    category: "Test Kit",
    stockQuantity: 12,
    unit: "kits",
    inStock: true,
  },
  {
    id: "10",
    name: "Typhoid Test Kit",
    brand: "Bio-Rad",
    price: 55.0,
    description: "Rapid typhoid fever diagnostic test kit",
    images: [
      "/product-images/Typhoid.png",
      "/product-images/med.png",
    ],
    category: "Test Kit",
    stockQuantity: 6,
    unit: "units",
    inStock: true,
  },
  {
    id: "11",
    name: "Pregnancy Test Kit",
    brand: "Johnson & Johnson",
    price: 18.0,
    description: "Home pregnancy test kit for early detection",
    images: [
      "/product-images/Pregenacy.png",
      "/product-images/med.png",
    ],
    category: "Test Kit",
    stockQuantity: 50,
    unit: "boxes",
    inStock: true,
  },
  {
    id: "12",
    name: "Ovulation Test Kit",
    brand: "Roche Diagnostics",
    price: 25.0,
    description: "Ovulation prediction test kit for fertility tracking",
    images: [
      "/product-images/Ovulation.png",
      "/product-images/med.png",
    ],
    category: "Test Kit",
    stockQuantity: 20,
    unit: "doses",
    inStock: true,
  },
  {
    id: "13",
    name: "Gonorrhea Test Kit",
    brand: "Quidel Technologies",
    price: 65.0,
    description: "Rapid gonorrhea diagnostic test kit",
    images: [
      "/product-images/Gonnorhea.png",
      "/product-images/med.png",
    ],
    category: "Test Kit",
    stockQuantity: 7,
    unit: "units",
    inStock: true,
  },
  {
    id: "14",
    name: "Drug Abuse Test Kit",
    brand: "Bio-Rad",
    price: 40.0,
    description: "Multi-panel drug abuse screening test kit",
    images: [
      "/product-images/DrugAbuse.png",
      "/product-images/med.png",
    ],
    category: "Test Kit",
    stockQuantity: 14,
    unit: "units",
    inStock: true,
  },
  {
    id: "15",
    name: "Vaginal Health Test Kit",
    brand: "Johnson & Johnson",
    price: 35.0,
    description: "Vaginal health screening test kit",
    images: [
      "/product-images/VagKit.png",
      "/product-images/med.png",
    ],
    category: "Test Kit",
    stockQuantity: 30,
    unit: "boxes",
    inStock: true,
  },
  {
    id: "16",
    name: "First Aid Kit - Premium",
    brand: "Johnson & Johnson",
    price: 45.0,
    description: "Comprehensive first aid kit for emergency situations",
    images: [
      "/product-images/firstAid2.png",
      "/product-images/firstAid3.png",
    ],
    category: "First Aid Supplies",
    stockQuantity: 25,
    unit: "kits",
    inStock: true,
  },
  {
    id: "17",
    name: "Advanced Malaria Test Kit",
    brand: "Abbott",
    price: 50.0,
    description: "Rapid malaria diagnostic test kit for accurate detection",
    images: [
      "/product-images/Malaria2.png",
      "/product-images/med.png",
    ],
    category: "Test Kit",
    stockQuantity: 2,
    unit: "boxes",
    inStock: true,
  },
]

export const categories = [
  "Test Kit",
  "Vaccines",
  "Antibiotics",
  "Vital Monitoring Devices",
  "Diagnostic Tools",
  "Medications",
  "Medical Materials",
  "Emergency Equipment",
  "Medical Consumables",
  "Rehabilitation Tools",
  "Wearable Tech",
  "First Aid Supplies",
  "Telehealth Devices",
  "Sanitation & PPE",
]

export const brands = ["Abbott", "Roche Diagnostics", "Bio-Rad", "Quidel Technologies", "Moderna", "Johnson & Johnson", "Omron", "Panga", "Easy Home", "CareTouch", "Agaro"]
