export interface Patient {
  id: number
  name: string
  dob: string
  gender: string
  contact: string
  condition: string
  lastVisit: string
  avatar?: string
  email?: string
  address?: string
}

export const patientsData: Patient[] = [
  {
    id: 1,
    name: "Olivia Rhye",
    dob: "9 Mar 2000",
    gender: "Female",
    contact: "0540777343",
    condition: "Asthma",
    lastVisit: "7 May, 2025",
    email: "olivia.rhye@email.com",
    address: "123 Main St, City",
  },
  {
    id: 2,
    name: "Phoenix Baker",
    dob: "15 Jun 1995",
    gender: "Male",
    contact: "0540888444",
    condition: "Diabetes",
    lastVisit: "12 May, 2025",
    email: "phoenix.baker@email.com",
    address: "456 Oak Ave, Town",
  },
  {
    id: 3,
    name: "Lana Steiner",
    dob: "22 Dec 1988",
    gender: "Female",
    contact: "0540999555",
    condition: "Hypertension",
    lastVisit: "18 May, 2025",
    email: "lana.steiner@email.com",
    address: "789 Pine Rd, Village",
  },
  {
    id: 4,
    name: "Demi Wilkinson",
    dob: "3 Aug 1992",
    gender: "Female",
    contact: "0540666777",
    condition: "Migraine",
    lastVisit: "20 May, 2025",
    email: "demi.wilkinson@email.com",
    address: "321 Elm St, District",
  },
  {
    id: 5,
    name: "Candice Wu",
    dob: "11 Feb 1985",
    gender: "Female",
    contact: "0540333444",
    condition: "Arthritis",
    lastVisit: "25 May, 2025",
    email: "candice.wu@email.com",
    address: "654 Maple Dr, County",
  },
  {
    id: 6,
    name: "Natali Craig",
    dob: "28 Sep 1990",
    gender: "Female",
    contact: "0540111222",
    condition: "Allergies",
    lastVisit: "30 May, 2025",
    email: "natali.craig@email.com",
    address: "987 Cedar Ln, Borough",
  },
  {
    id: 7,
    name: "Drew Cano",
    dob: "7 Jan 1987",
    gender: "Male",
    contact: "0540555666",
    condition: "Back Pain",
    lastVisit: "2 Jun, 2025",
    email: "drew.cano@email.com",
    address: "147 Birch St, Township",
  },
  {
    id: 8,
    name: "Orlando Diggs",
    dob: "19 Apr 1993",
    gender: "Male",
    contact: "0540777888",
    condition: "Anxiety",
    lastVisit: "5 Jun, 2025",
    email: "orlando.diggs@email.com",
    address: "258 Spruce Ave, Municipality",
  },
  {
    id: 9,
    name: "Andi Lane",
    dob: "14 Nov 1991",
    gender: "Non-binary",
    contact: "0540999000",
    condition: "Depression",
    lastVisit: "8 Jun, 2025",
    email: "andi.lane@email.com",
    address: "369 Willow Rd, Hamlet",
  },
  {
    id: 10,
    name: "Kate Morrison",
    dob: "26 May 1989",
    gender: "Female",
    contact: "0540222333",
    condition: "Insomnia",
    lastVisit: "10 Jun, 2025",
    email: "kate.morrison@email.com",
    address: "741 Ash Dr, Settlement",
  },
  {
    id: 11,
    name: "Koray Okumus",
    dob: "8 Oct 1994",
    gender: "Male",
    contact: "0540444555",
    condition: "High Cholesterol",
    lastVisit: "12 Jun, 2025",
    email: "koray.okumus@email.com",
    address: "852 Poplar St, Community",
  },
  {
    id: 12,
    name: "Melody Macy",
    dob: "17 Jul 1986",
    gender: "Female",
    contact: "0540666888",
    condition: "Thyroid Issues",
    lastVisit: "15 Jun, 2025",
    email: "melody.macy@email.com",
    address: "963 Hickory Ln, Locality",
  },
]
