name: Deploy to VPS (No Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
        script: |
          echo "🚀 Starting deployment without Docker..."
          
          # Set environment variables
          export MONGODB_URI="${{ secrets.MONGODB_URI }}"
          export JWT_SECRET="${{ secrets.JWT_SECRET }}"
          
          # Download deployment script
          echo "📥 Downloading deployment script..."
          wget -O deploy-no-docker.sh https://raw.githubusercontent.com/ekow1/Kulobal-Health-Demo/main/deploy-no-docker.sh
          chmod +x deploy-no-docker.sh
          
          # Run deployment
          echo "🚀 Running deployment..."
          ./deploy-no-docker.sh
          
          # Show final status
          echo "📊 Final application status:"
          pm2 status
          
          echo "✅ Deployment completed successfully!"
          echo "🌐 API is available at: https://server.ekowlabs.space"
